# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-24-node8-alpha #confirm the latest docker image :)
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
    general:
      artifacts:
        - "app/build/reports/androidTests/connected"

    machine:
      java:
        version: oraclejdk8
      python:
        version: 2.7.10
      environment:
        GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
        TEST_FLAGS: "--configure-on-demand -PdisablePreDex"
        TERM: "dumb"
        ADB_INSTALL_TIMEOUT: "10"

    dependencies:
      pre:
        - if [ ! -e /usr/local/android-sdk-linux/build-tools/25.0.2 ]; then echo y | android update sdk --all --no-ui --filter "build-tools-25.0.2"; fi;
        - if [ ! -e /usr/local/android-sdk-linux/platforms/android-25 ]; then echo y | android update sdk --all --no-ui --filter "android-25"; fi;
        - if ! $(grep -q "Revision=44.0.0" /usr/local/android-sdk-linux/extras/android/m2repository/source.properties); then echo y | android update sdk --all --no-ui --filter "extra-android-m2repository"; fi;
      cache_directories:
        - /usr/local/android-sdk-linux/build-tools/25.0.2
        - /usr/local/android-sdk-linux/platforms/android-25
        - /usr/local/android-sdk-linux/extras/android/m2repository

    test:
      override:
        - ./gradlew assembleDebug -PdisablePreDex

    deployment:
      espresso:
        branch: master
        commands:
          - emulator -avd circleci-android22 -no-audio -no-window:
              background: true
              parallel: true
          # wait for it to have booted
          - circle-android wait-for-boot
          # unlock the emulator screen
          - sleep 30
          - adb shell input keyevent 82
          # run tests  against the emulator.
          - ./gradlew connectedAndroidTest -PdisablePreDex
          # copy the build outputs to artifacts
          - cp -r app/build/outputs $CIRCLE_ARTIFACTS
          # copy the test results to the test results directory.
          - cp -r app/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS